### ISSUE TITLE
réglage du htaccess

### ISSUE THREAD

**Issue by mingarao** [ccahier/weboai#5]
Actuellement pb : 

- avec le htaccess, erreur 500 sur toutes les pages du site
- sans le htaccess, site fonctionnel mais erreur 404 sur les pages de type http://monDomaine/weboai/set/maCollection/

= réglage dans la conf d'apache à repréciser ? autre problème ?

**Comment by glorieux-f** [comment]
Le htaccess fonctionne sur d’autres serveurs, à voir.
Par contre, dans ce qui dépend de moi, je peux autoriser des adressages de type 
?set=monset&record=mondoc

**Comment by mingarao** [comment]
Oui pour le moment cce serait pas mal cette solution ça permettrait de contourner le pb et de reprendre la question des url propres plus tard. 
Je pense que je n'ai pas changé ce qu'il faut dans la conf apache (on avait d'ailleurs fait la même erreur samedi à Paris, pas changé le `AllowOverride All` au bon endroit. Sauf que je ne me rappelle plus kikoikès !)

**Comment by glorieux-f** [comment]
* git pull
* cp _index.php index.php
* mv .htaccess .htKO

Normalement ça doit marcher.

Si tu trouves pour les RewriteRule, il suffit de remettre le .htaccess pour que l’adressage fonctionne comme avant.

Dès que tu dis que ça marche, je referme l‘issue.

**Comment by mingarao** [comment]
It works :+1: 


![collection](https://cloud.githubusercontent.com/assets/6703169/26213330/e8ba5d64-3bf8-11e7-8d6c-dbdc72d6f7b1.png)
